### ISSUE TITLE
RN0.19可以显示地图但是无法显示marker

### ISSUE THREAD

**Issue by xuyannan** [hufeng/react-native-baidu-map#11]
RT，地图可以正常显示，但是无法显示marker，设置普通/卫星模式以及热力图都无效。
求回复~

**Comment by xuyannan** [comment]
估计 @hufeng 太忙，自己解决：

`BaiduMapViewManager.java` 中，
`import com.facebook.react.uimanager.ReactProp;`
替换为
`import com.facebook.react.uimanager.annotations.ReactProp;`

同时修改BaiduMapKit项目的`build.gradle`

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.1.1'
    // compile 'com.facebook.react:react-native:0.14.+'
    compile 'com.facebook.react:react-native:0.19.1'    // <--修改RN版本
}
```

**Comment by chenchuanjiang** [comment]
请问一下，我在react-native 0.20.0版本中，跳转地图界面的时候就卡死了，然后工程就stopped，请问一下，这个问题你知道怎么解决吗？

**Comment by xuyannan** [comment]
@chenchuanjiang 0.20.0版本还没试过。
