### ISSUE TITLE
什么时候出IOS版本呢？可以加微信吗？

### ISSUE THREAD

**Issue by jasondu** [hufeng/react-native-baidu-map#5]

**Comment by tyao1** [comment]
同求

**Comment by tyao1** [comment]
https://github.com/nogic/ReactNativeStudy 这个项目里有个IOS版本的百度地图

**Comment by jasondu** [comment]
谢谢

**Comment by hufeng** [comment]
赞！我们内部已经写好了iOS 还没有放出来，包括和支付宝和微信支付 全都打通了 已经在项目中使用 我们在生产环境再稳定下 然后可以放出来 确保不吭小伙伴 :+1:
